### ISSUE TITLE
v6 Beta - Support for presentation and custom opensong formats

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#227] opened 2023-04-20 09:19 UTC
Data:
v5 supports
Image (png, jpeg...),
PDF (single and multi page),
custom slides (with timer), 
scripture,
image slideshow (with timer)

These display on the primary and secondary screens as appropriate for the mode in use.

All of these formats can be edited in v5 after creation. at least, using basic edit - the user may need to understand how user fields are used to adjust looping and timers if not in presentation mode.

Whilst some formats are more relevant to presentation they are viewable (at least basic display) in all modes .  A user of a shared set can reasonably be in any mode.

v6 fork does not yet support display and edit of all expected formats giving degraded abilities.

This can be addressed for each format to ensure all modes, all screens (primary and secondary, local and connected) display content in a reasonable way.  The complexity of screens and modes makes testing a major part of the work.

**Comment by thebigg73** [comment] 2023-04-20 14:38
Hi Ian,

I've been working through this - most of the logic was there and believe it or not most of the issues are caused by theme colours not being respected.  I was using dark theme and when I switched to light theme I couldn't seen anything.  Anyway, I've fixed that but not committed yet as I need your advice.

When using a secondary display what would you expect for each mode in terms of second display colours/fonts?
I will start by saying Performance mode (least likely to use second display) should use the same fonts, colours etc as in performance mode since it shows all sections and hightlighted backgrounds etc.

Presenter mode, does (and I think rightly) uses the presenter colours in the theme and the fonts described

My uncertainty comes around stage mode.  Should it follow the presenter mode or the performance mode for second screen colours?  I know you use this mode extensively, so wanted to confirm the best method (not necessarily what v5 uses).  I'm leaning towards presenter mode output, but will go with what you say!

**Comment by iv-gha** [comment] 2023-04-20 15:46
We have the stage/presentation colors / fonts  for use with second screen in these modes (I note we do not have a second screen capo color - probably should have).  v5 keeps the behaviour of second screen display the same - with 'connected display' settings respected (backgrounds, margins, positions, bold, chords,  shadow etc.).

**Comment by thebigg73** [comment] 2023-04-20 19:40
Ok, that should be everything fixed for this one. 

- All 'songs': Songs, notes, slides, image slides, images, pdfs, scriptures working in main screen and secondary screen in all modes (Performance, Stage and Presenter)
- Secondary display now uses PresoColors and PresoFonts when not in Performance mode
- Added in presentation capo colour user setting

Let me know if not!

**Comment by thebigg73** [comment] 2023-04-20 19:41
Also fixed a few other bugs and things not updating properly while doing this
I've also change the background in Stage Mode to not be the colorPrimary, but a reduced alpha of the lyrics background colour.  This should make light themes more light!

**Comment by thebigg73** [comment] 2023-04-20 19:41
Sorry - didn't mean to close!

**Closed as completed** 2023-12-25 11:28 UTC
Labels: fixed but not confirmed
